### ISSUE TITLE
自己完結exe

### ISSUE THREAD

**Issue by forver-alone** [asukaze55/cassava-editor#2]
自己完結exeを作成する時、Release_Buildフォルダの直下に.oと.dファイルが生成されます。

確認したいですが、どのようなコマンドや方法を使用すれば自己完結exeのみを生成できますか？

**Comment by asukaze55** [comment]
.o や .dファイルは .exe を作成するために必要となる中間ファイルです。
.exe が生成された後は削除しても問題ありません。
.o や .dファイルは特に気にせず、.exe ファイルのみを好きな場所にコピーして利用していただければよいかと思います。
よろしくお願いします。
